version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  app:
    image: andris741/python-beadando
    environment:
      DB_URL: 'mysql+mysqlconnector://root:rootpassword@mysql_db:3306/app_db'
      APP_SECRET: "my_full_random_secret_key_123"
    container_name: python_app
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data:
